
spring:
  profiles:
    active: dev

---
#spring的配置
spring:
  port: 8201
  profiles: dev
  application:
    name: springcloud-provider-dept
#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

---
spring:
  port: 8202
  profiles: test
  application:
    name: springcloud-provider-dept

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/